name: Tests
on:
  - push
  - pull_request

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/todos
    services:
      database:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: todos
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install sqlx
      run: cargo install sqlx-cli
    - name: Run migrations
      run: sqlx migrate run
    - name: Build application
      run: cargo build
    - name: Start rust server
      run: cargo run &
    - name: Install bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      run: make e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  rust-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Fetch dependencies
      run: cargo fetch
    - name: Build application
      run: cargo build --offline --verbose
    - name: Test application
      run: cargo test --offline --verbose
